### ISSUE TITLE
github community stuff

### ISSUE THREAD

**Issue by thorade** [TechnicalBuildingSystems/BuildingControlLib#2]
You should add a couple of files, most importantly a License.md file.
The easiest way is to do it via the github web interface: 
next to the green clone/download button, there is a button create new file, 
click that and start to type LICENSE.md, then some dropdown menu will appear.
https://help.github.com/articles/adding-a-license-to-a-repository/
https://choosealicense.com/

Also, have a look at this page (it is visible only to the repo owner):
https://github.com/TechnicalBuildingSystems/BuildingControlLib/community

**Comment by thorade** [comment]
Oh, and maybe you want to reconsider using the Modelica license:
https://github.com/impact/impact/blob/master/resources/docs/modelica2015/paper/impact.md#which-license-is-best-for-your-library
https://github.com/search?q=modelica+license&type=Issues&utf8=%E2%9C%93

If you use one of the many standard licenses, github will display it in the top right corner:
https://github.com/blog/2252-license-now-displayed-on-repository-overview

**Comment by GeorgFerdinandSchneider** [comment]
I added a licence file through 650c6e16371458afece4f7bf4f63e2e1418fcea4

**Comment by GeorgFerdinandSchneider** [comment]
closed

**Comment by thorade** [comment]
The MSL will be switching to BSD 3-clause, it seems:
https://github.com/modelica/Modelica/issues/2320
https://choosealicense.com/licenses/bsd-3-clause/
