### ISSUE TITLE
git tag v0.9.4

### ISSUE THREAD

**Issue by thorade** [TechnicalBuildingSystems/BuildingControlLib#3]
Once @dietmarw (is that correct?) has taken notice of this repository, chances are good it will get listed here:
https://modelica.org/libraries
http://impact.modelica.org/libraries.html

If you want a blue button instead of a grey N/A, you need to use git to assign a version tag to some commit of your choice. As a tag, use something like `v0.4.2`, that is a lowercase v and three numbers seperated by dots (breaking.feature.fix). That is not perfect, but good.
http://semver.org/

**Comment by GeorgFerdinandSchneider** [comment]
Thanks for this comment! I just created a pre-release-

resolved
